"""Criação das tabelas corrigida

Revision ID: 04505543e60b
Revises: 5c623c90f47b
Create Date: 2025-06-10 22:04:00.341928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04505543e60b'
down_revision: Union[str, None] = '5c623c90f47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoriafenomeno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explicacao_possivel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel_misterio', sa.Integer(), nullable=False),
    sa.Column('popularidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entidadesobrenatural',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periculosidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aparicoes_confirmadas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_ocorrencia', sa.Date(), nullable=False),
    sa.Column('localizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_fenomeno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoriafenomeno.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidadesobrenatural.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registromultimidia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('legenda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relato_id'], ['relato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testemunha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credibilidade', sa.Integer(), nullable=False),
    sa.Column('tipo_relacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiencia_previa', sa.Boolean(), nullable=False),
    sa.Column('relato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relato_id'], ['relato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testemunha')
    op.drop_table('registromultimidia')
    op.drop_table('relato')
    op.drop_table('entidadesobrenatural')
    op.drop_table('categoriafenomeno')
    # ### end Alembic commands ###
