"""Adiciona campo tipo em entidade

Revision ID: 9cff2199feea
Revises: 04505543e60b
Create Date: 2025-06-11 14:39:51.255556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9cff2199feea'
down_revision: Union[str, None] = '04505543e60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entidadesobrenatural', sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entidadesobrenatural', 'tipo')
    # ### end Alembic commands ###
